suppressMessages(library(ggplot2))


fn = "plannergraphdistedges"
gp = read.csv(paste(fn,".csv",sep=""))
png(paste(fn, "dadbl.png" ,sep=""))
ggplot(data = gp, aes(x=factor(gp$time), y=gp$ad)) + labs( x="Level", y="Distribution all degree" ) + geom_violin()  + geom_boxplot(width=0.05) + theme(text = element_text(size=20))
graphics.off()
png(paste(fn, "didbl.png" ,sep=""))
ggplot(data = gp, aes(x=factor(gp$time), y=gp$ind)) + labs( x="Level", y="Distribution in degree" ) + geom_violin()  + geom_boxplot(width=0.05) + theme(text = element_text(size=20))
graphics.off()
png(paste(fn, "dodbl.png" ,sep=""))
ggplot(data = gp, aes(x=factor(gp$time), y=gp$otd)) + labs( x="Level", y="Distribution out degree" ) + geom_violin()  + geom_boxplot(width=0.05) + theme(text = element_text(size=20))
graphics.off()
png(paste(fn, "dbcbl.png" ,sep=""))
ggplot(data = gp, aes(x=factor(gp$time), y=gp$bc)) + labs( x="Level", y="Distribution betweenness centrality" ) + geom_violin()  + geom_boxplot(width=0.05) + theme(text = element_text(size=20))
graphics.off()


png(paste(fn, "dad.png" ,sep=""))
hist(gp$ad)
graphics.off()
png(paste(fn, "did.png" ,sep=""))
hist(gp$ind)
graphics.off()
png(paste(fn, "dod.png" ,sep=""))
hist(gp$otd)
graphics.off()
png(paste(fn, "dbc.png" ,sep=""))
hist(gp$bc)
graphics.off()
